# Generated by Django 4.2.9 on 2024-04-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
