# Generated by Django 4.2.9 on 2024-04-02 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_remove_userprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('material_educativo', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carrera')),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materia_asignada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
