# Generated by Django 4.2.9 on 2024-04-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carrera_materia_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.carrera'),
        ),
    ]
