# Generated by Django 4.2.9 on 2024-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_carrera_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/carrera/materia'),
        ),
    ]
