# Generated by Django 4.2.9 on 2024-04-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_materia_material_educativo_materialeducativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialeducativo',
            name='nombreMaterial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
