# Generated by Django 4.2.9 on 2024-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_materialeducativo_nombrematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioclase',
            name='dia_semana',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10),
        ),
    ]
