# Generated by Django 4.2.9 on 2024-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_horarioclase_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='enlace_zoom',
            field=models.URLField(blank=True, null=True),
        ),
    ]
