# Generated by Django 4.2.9 on 2024-04-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
