# Generated by Django 4.2.9 on 2024-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='hilo_conversacion',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
