# Generated by Django 4.2.9 on 2024-04-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_mensaje_hilo_conversacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiloConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios', models.ManyToManyField(related_name='hilos_conversacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='hilo_conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hiloconversacion'),
        ),
    ]
