# Generated by Django 4.2.9 on 2024-04-07 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_hiloconversacion_alter_mensaje_hilo_conversacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalPrivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canales_usuario1', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canales_usuario2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='emisor',
            new_name='remitente',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='hilo_conversacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.DeleteModel(
            name='HiloConversacion',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='home.canalprivado'),
        ),
    ]
